// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getFileById = `-- name: GetFileById :one
SELECT id, session_id, file_name, file_type, file_size, original_path, source_path, translated_path, char_count, page_count, style, model_used, status, error_msg, created_at, updated_at FROM files WHERE id = ? LIMIT 1
`

func (q *Queries) GetFileById(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileById, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.OriginalPath,
		&i.SourcePath,
		&i.TranslatedPath,
		&i.CharCount,
		&i.PageCount,
		&i.Style,
		&i.ModelUsed,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFile = `-- name: InsertFile :exec
INSERT INTO files (
  id, session_id, file_name, file_type, file_size, original_path, source_path, translated_path,
  char_count, page_count, style, model_used, status, error_msg, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertFileParams struct {
	ID             string         `json:"id"`
	SessionID      string         `json:"session_id"`
	FileName       string         `json:"file_name"`
	FileType       string         `json:"file_type"`
	FileSize       int64          `json:"file_size"`
	OriginalPath   sql.NullString `json:"original_path"`
	SourcePath     sql.NullString `json:"source_path"`
	TranslatedPath sql.NullString `json:"translated_path"`
	CharCount      sql.NullInt64  `json:"char_count"`
	PageCount      sql.NullInt64  `json:"page_count"`
	Style          sql.NullString `json:"style"`
	ModelUsed      sql.NullString `json:"model_used"`
	Status         string         `json:"status"`
	ErrorMsg       sql.NullString `json:"error_msg"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) error {
	_, err := q.db.ExecContext(ctx, insertFile,
		arg.ID,
		arg.SessionID,
		arg.FileName,
		arg.FileType,
		arg.FileSize,
		arg.OriginalPath,
		arg.SourcePath,
		arg.TranslatedPath,
		arg.CharCount,
		arg.PageCount,
		arg.Style,
		arg.ModelUsed,
		arg.Status,
		arg.ErrorMsg,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateFileExtracted = `-- name: UpdateFileExtracted :exec
UPDATE files
SET source_path = ?, char_count = ?, page_count = ?, updated_at = ?
WHERE id = ?
`

type UpdateFileExtractedParams struct {
	SourcePath sql.NullString `json:"source_path"`
	CharCount  sql.NullInt64  `json:"char_count"`
	PageCount  sql.NullInt64  `json:"page_count"`
	UpdatedAt  string         `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateFileExtracted(ctx context.Context, arg UpdateFileExtractedParams) error {
	_, err := q.db.ExecContext(ctx, updateFileExtracted,
		arg.SourcePath,
		arg.CharCount,
		arg.PageCount,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateFileStatus = `-- name: UpdateFileStatus :exec
UPDATE files SET status = ?, error_msg = ?, updated_at = ? WHERE id = ?
`

type UpdateFileStatusParams struct {
	Status    string         `json:"status"`
	ErrorMsg  sql.NullString `json:"error_msg"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateFileStatus(ctx context.Context, arg UpdateFileStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFileStatus,
		arg.Status,
		arg.ErrorMsg,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateFileTranslated = `-- name: UpdateFileTranslated :exec
UPDATE files
SET source_path = ?, translated_path = ?, status = ?, char_count = ?, page_count = ?, model_used = ?, updated_at = ?
WHERE id = ?
`

type UpdateFileTranslatedParams struct {
	SourcePath     sql.NullString `json:"source_path"`
	TranslatedPath sql.NullString `json:"translated_path"`
	Status         string         `json:"status"`
	CharCount      sql.NullInt64  `json:"char_count"`
	PageCount      sql.NullInt64  `json:"page_count"`
	ModelUsed      sql.NullString `json:"model_used"`
	UpdatedAt      string         `json:"updated_at"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateFileTranslated(ctx context.Context, arg UpdateFileTranslatedParams) error {
	_, err := q.db.ExecContext(ctx, updateFileTranslated,
		arg.SourcePath,
		arg.TranslatedPath,
		arg.Status,
		arg.CharCount,
		arg.PageCount,
		arg.ModelUsed,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
