// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: glossary.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const clearFileGlossary = `-- name: ClearFileGlossary :exec
UPDATE glossary_entries SET current_file_name = NULL, updated_at = ?
WHERE current_file_name = ?
`

type ClearFileGlossaryParams struct {
	UpdatedAt       string         `json:"updated_at"`
	CurrentFileName sql.NullString `json:"current_file_name"`
}

func (q *Queries) ClearFileGlossary(ctx context.Context, arg ClearFileGlossaryParams) error {
	_, err := q.db.ExecContext(ctx, clearFileGlossary, arg.UpdatedAt, arg.CurrentFileName)
	return err
}

const createGlossaryEntry = `-- name: CreateGlossaryEntry :exec
INSERT INTO glossary_entries (id, source_lang, target_lang, target, doc_type, status, current_file_name, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateGlossaryEntryParams struct {
	ID              string         `json:"id"`
	SourceLang      string         `json:"source_lang"`
	TargetLang      string         `json:"target_lang"`
	Target          string         `json:"target"`
	DocType         sql.NullString `json:"doc_type"`
	Status          string         `json:"status"`
	CurrentFileName sql.NullString `json:"current_file_name"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

func (q *Queries) CreateGlossaryEntry(ctx context.Context, arg CreateGlossaryEntryParams) error {
	_, err := q.db.ExecContext(ctx, createGlossaryEntry,
		arg.ID,
		arg.SourceLang,
		arg.TargetLang,
		arg.Target,
		arg.DocType,
		arg.Status,
		arg.CurrentFileName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createGlossaryVariant = `-- name: CreateGlossaryVariant :exec
INSERT OR IGNORE INTO glossary_variants (id, entry_id, source) VALUES (?, ?, ?)
`

type CreateGlossaryVariantParams struct {
	ID      string `json:"id"`
	EntryID string `json:"entry_id"`
	Source  string `json:"source"`
}

func (q *Queries) CreateGlossaryVariant(ctx context.Context, arg CreateGlossaryVariantParams) error {
	_, err := q.db.ExecContext(ctx, createGlossaryVariant, arg.ID, arg.EntryID, arg.Source)
	return err
}

const createTranslationRule = `-- name: CreateTranslationRule :exec
INSERT INTO translation_rules (id, name, content, doc_type, target_lang, enabled, sort_order, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTranslationRuleParams struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Content    string         `json:"content"`
	DocType    sql.NullString `json:"doc_type"`
	TargetLang sql.NullString `json:"target_lang"`
	Enabled    int64          `json:"enabled"`
	SortOrder  int64          `json:"sort_order"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
}

func (q *Queries) CreateTranslationRule(ctx context.Context, arg CreateTranslationRuleParams) error {
	_, err := q.db.ExecContext(ctx, createTranslationRule,
		arg.ID,
		arg.Name,
		arg.Content,
		arg.DocType,
		arg.TargetLang,
		arg.Enabled,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteGlossaryEntry = `-- name: DeleteGlossaryEntry :exec
DELETE FROM glossary_entries WHERE id = ?
`

func (q *Queries) DeleteGlossaryEntry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGlossaryEntry, id)
	return err
}

const deleteTranslationRule = `-- name: DeleteTranslationRule :exec
DELETE FROM translation_rules WHERE id = ?
`

func (q *Queries) DeleteTranslationRule(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTranslationRule, id)
	return err
}

const deleteVariantsByEntry = `-- name: DeleteVariantsByEntry :exec
DELETE FROM glossary_variants WHERE entry_id = ?
`

func (q *Queries) DeleteVariantsByEntry(ctx context.Context, entryID string) error {
	_, err := q.db.ExecContext(ctx, deleteVariantsByEntry, entryID)
	return err
}

const findEntryBySourceAndDocType = `-- name: FindEntryBySourceAndDocType :one
SELECT e.id, e.source_lang, e.target_lang, e.target, e.doc_type, e.status, e.current_file_name, e.created_at, e.updated_at
FROM glossary_entries e
JOIN glossary_variants v ON v.entry_id = e.id
WHERE v.source = ?
  AND e.source_lang = ?
  AND e.target_lang = ?
  AND e.doc_type = ?
LIMIT 1
`

type FindEntryBySourceAndDocTypeParams struct {
	Source     string         `json:"source"`
	SourceLang string         `json:"source_lang"`
	TargetLang string         `json:"target_lang"`
	DocType    sql.NullString `json:"doc_type"`
}

type FindEntryBySourceAndDocTypeRow struct {
	ID              string         `json:"id"`
	SourceLang      string         `json:"source_lang"`
	TargetLang      string         `json:"target_lang"`
	Target          string         `json:"target"`
	DocType         sql.NullString `json:"doc_type"`
	Status          string         `json:"status"`
	CurrentFileName sql.NullString `json:"current_file_name"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

// FindEntryBySourceAndDocType finds a glossary entry matching a source variant and doc_type.
// Used to check for duplicates before inserting.
func (q *Queries) FindEntryBySourceAndDocType(ctx context.Context, arg FindEntryBySourceAndDocTypeParams) (FindEntryBySourceAndDocTypeRow, error) {
	row := q.db.QueryRowContext(ctx, findEntryBySourceAndDocType,
		arg.Source,
		arg.SourceLang,
		arg.TargetLang,
		arg.DocType,
	)
	var i FindEntryBySourceAndDocTypeRow
	err := row.Scan(
		&i.ID,
		&i.SourceLang,
		&i.TargetLang,
		&i.Target,
		&i.DocType,
		&i.Status,
		&i.CurrentFileName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGlossaryEntry = `-- name: GetGlossaryEntry :one
SELECT id, source_lang, target_lang, target, doc_type, status, created_at, updated_at, current_file_name FROM glossary_entries WHERE id = ? LIMIT 1
`

func (q *Queries) GetGlossaryEntry(ctx context.Context, id string) (GlossaryEntry, error) {
	row := q.db.QueryRowContext(ctx, getGlossaryEntry, id)
	var i GlossaryEntry
	err := row.Scan(
		&i.ID,
		&i.SourceLang,
		&i.TargetLang,
		&i.Target,
		&i.DocType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentFileName,
	)
	return i, err
}

const insertDocType = `-- name: InsertDocType :exec
INSERT OR IGNORE INTO doc_types (id, name) VALUES (?, ?)
`

type InsertDocTypeParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) InsertDocType(ctx context.Context, arg InsertDocTypeParams) error {
	_, err := q.db.ExecContext(ctx, insertDocType, arg.ID, arg.Name)
	return err
}

const listDocTypes = `-- name: ListDocTypes :many
SELECT id, name FROM doc_types ORDER BY name
`

func (q *Queries) ListDocTypes(ctx context.Context) ([]DocType, error) {
	rows, err := q.db.QueryContext(ctx, listDocTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocType{}
	for rows.Next() {
		var i DocType
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlossaryEntries = `-- name: ListGlossaryEntries :many
SELECT id, source_lang, target_lang, target, doc_type, status, created_at, updated_at, current_file_name FROM glossary_entries ORDER BY created_at DESC
`

func (q *Queries) ListGlossaryEntries(ctx context.Context) ([]GlossaryEntry, error) {
	rows, err := q.db.QueryContext(ctx, listGlossaryEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlossaryEntry{}
	for rows.Next() {
		var i GlossaryEntry
		if err := rows.Scan(
			&i.ID,
			&i.SourceLang,
			&i.TargetLang,
			&i.Target,
			&i.DocType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentFileName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslationRules = `-- name: ListTranslationRules :many
SELECT id, name, content, doc_type, target_lang, enabled, sort_order, created_at, updated_at FROM translation_rules ORDER BY sort_order, created_at
`

func (q *Queries) ListTranslationRules(ctx context.Context) ([]TranslationRule, error) {
	rows, err := q.db.QueryContext(ctx, listTranslationRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranslationRule{}
	for rows.Next() {
		var i TranslationRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.DocType,
			&i.TargetLang,
			&i.Enabled,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByEntry = `-- name: ListVariantsByEntry :many
SELECT id, entry_id, source FROM glossary_variants WHERE entry_id = ? ORDER BY source
`

func (q *Queries) ListVariantsByEntry(ctx context.Context, entryID string) ([]GlossaryVariant, error) {
	rows, err := q.db.QueryContext(ctx, listVariantsByEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlossaryVariant{}
	for rows.Next() {
		var i GlossaryVariant
		if err := rows.Scan(&i.ID, &i.EntryID, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadActiveRules = `-- name: LoadActiveRules :many
SELECT id, name, content, doc_type, target_lang, enabled, sort_order, created_at, updated_at FROM translation_rules
WHERE enabled = 1
  AND (doc_type IS NULL OR doc_type = ?)
  AND (target_lang IS NULL OR target_lang = ?)
ORDER BY sort_order
`

type LoadActiveRulesParams struct {
	DocType    sql.NullString `json:"doc_type"`
	TargetLang sql.NullString `json:"target_lang"`
}

func (q *Queries) LoadActiveRules(ctx context.Context, arg LoadActiveRulesParams) ([]TranslationRule, error) {
	rows, err := q.db.QueryContext(ctx, loadActiveRules, arg.DocType, arg.TargetLang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranslationRule{}
	for rows.Next() {
		var i TranslationRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.DocType,
			&i.TargetLang,
			&i.Enabled,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadGlossaryForFile = `-- name: LoadGlossaryForFile :many
SELECT v.source, e.target
FROM glossary_variants v
JOIN glossary_entries e ON v.entry_id = e.id
WHERE e.current_file_name = ?
ORDER BY e.id, v.source
`

type LoadGlossaryForFileRow struct {
	Source string `json:"source"`
	Target string `json:"target"`
}

func (q *Queries) LoadGlossaryForFile(ctx context.Context, currentFileName sql.NullString) ([]LoadGlossaryForFileRow, error) {
	rows, err := q.db.QueryContext(ctx, loadGlossaryForFile, currentFileName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadGlossaryForFileRow{}
	for rows.Next() {
		var i LoadGlossaryForFileRow
		if err := rows.Scan(&i.Source, &i.Target); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGlossaryCurrentFile = `-- name: SetGlossaryCurrentFile :exec
UPDATE glossary_entries SET current_file_name = ?, updated_at = ? WHERE id = ?
`

type SetGlossaryCurrentFileParams struct {
	CurrentFileName sql.NullString `json:"current_file_name"`
	UpdatedAt       string         `json:"updated_at"`
	ID              string         `json:"id"`
}

func (q *Queries) SetGlossaryCurrentFile(ctx context.Context, arg SetGlossaryCurrentFileParams) error {
	_, err := q.db.ExecContext(ctx, setGlossaryCurrentFile, arg.CurrentFileName, arg.UpdatedAt, arg.ID)
	return err
}

const updateGlossaryEntryStatus = `-- name: UpdateGlossaryEntryStatus :exec
UPDATE glossary_entries SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateGlossaryEntryStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateGlossaryEntryStatus(ctx context.Context, arg UpdateGlossaryEntryStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateGlossaryEntryStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const updateTranslationRule = `-- name: UpdateTranslationRule :exec
UPDATE translation_rules
SET name = ?, content = ?, doc_type = ?, target_lang = ?, enabled = ?, sort_order = ?, updated_at = ?
WHERE id = ?
`

type UpdateTranslationRuleParams struct {
	Name       string         `json:"name"`
	Content    string         `json:"content"`
	DocType    sql.NullString `json:"doc_type"`
	TargetLang sql.NullString `json:"target_lang"`
	Enabled    int64          `json:"enabled"`
	SortOrder  int64          `json:"sort_order"`
	UpdatedAt  string         `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateTranslationRule(ctx context.Context, arg UpdateTranslationRuleParams) error {
	_, err := q.db.ExecContext(ctx, updateTranslationRule,
		arg.Name,
		arg.Content,
		arg.DocType,
		arg.TargetLang,
		arg.Enabled,
		arg.SortOrder,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
