// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getMaxDisplayOrder = `-- name: GetMaxDisplayOrder :one
SELECT COALESCE(MAX(display_order), 0) AS max_order FROM messages WHERE session_id = ?
`

func (q *Queries) GetMaxDisplayOrder(ctx context.Context, sessionID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxDisplayOrder, sessionID)
	var max_order interface{}
	err := row.Scan(&max_order)
	return max_order, err
}

const getMessageById = `-- name: GetMessageById :one
SELECT id, session_id, role, display_order, display_mode, original_content, translated_content, file_id, source_lang, target_lang, style, model_used, original_message_id, tokens, created_at, updated_at FROM messages WHERE id = ? LIMIT 1
`

func (q *Queries) GetMessageById(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageById, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.DisplayOrder,
		&i.DisplayMode,
		&i.OriginalContent,
		&i.TranslatedContent,
		&i.FileID,
		&i.SourceLang,
		&i.TargetLang,
		&i.Style,
		&i.ModelUsed,
		&i.OriginalMessageID,
		&i.Tokens,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessagesBySessionCursor = `-- name: GetMessagesBySessionCursor :many
SELECT id, session_id, role, display_order, display_mode, original_content, translated_content, file_id, source_lang, target_lang, style, model_used, original_message_id, tokens, created_at, updated_at FROM messages
WHERE session_id = ?1
  AND (?2 = 0 OR display_order < ?3)
ORDER BY display_order DESC
LIMIT ?4
`

type GetMessagesBySessionCursorParams struct {
	SessionID    string      `json:"session_id"`
	Cursor       interface{} `json:"cursor"`
	CursorBefore int64       `json:"cursor_before"`
	RowLimit     int64       `json:"row_limit"`
}

func (q *Queries) GetMessagesBySessionCursor(ctx context.Context, arg GetMessagesBySessionCursorParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesBySessionCursor,
		arg.SessionID,
		arg.Cursor,
		arg.CursorBefore,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.DisplayOrder,
			&i.DisplayMode,
			&i.OriginalContent,
			&i.TranslatedContent,
			&i.FileID,
			&i.SourceLang,
			&i.TargetLang,
			&i.Style,
			&i.ModelUsed,
			&i.OriginalMessageID,
			&i.Tokens,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (
  id, session_id, role, display_order, display_mode,
  original_content, translated_content, file_id, source_lang, target_lang,
  style, model_used, original_message_id, tokens, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	ID                string         `json:"id"`
	SessionID         string         `json:"session_id"`
	Role              string         `json:"role"`
	DisplayOrder      int64          `json:"display_order"`
	DisplayMode       string         `json:"display_mode"`
	OriginalContent   string         `json:"original_content"`
	TranslatedContent sql.NullString `json:"translated_content"`
	FileID            sql.NullString `json:"file_id"`
	SourceLang        sql.NullString `json:"source_lang"`
	TargetLang        sql.NullString `json:"target_lang"`
	Style             sql.NullString `json:"style"`
	ModelUsed         sql.NullString `json:"model_used"`
	OriginalMessageID sql.NullString `json:"original_message_id"`
	Tokens            sql.NullInt64  `json:"tokens"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.DisplayOrder,
		arg.DisplayMode,
		arg.OriginalContent,
		arg.TranslatedContent,
		arg.FileID,
		arg.SourceLang,
		arg.TargetLang,
		arg.Style,
		arg.ModelUsed,
		arg.OriginalMessageID,
		arg.Tokens,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateMessageTranslated = `-- name: UpdateMessageTranslated :exec
UPDATE messages
SET translated_content = ?, tokens = ?, updated_at = ?
WHERE id = ?
`

type UpdateMessageTranslatedParams struct {
	TranslatedContent sql.NullString `json:"translated_content"`
	Tokens            sql.NullInt64  `json:"tokens"`
	UpdatedAt         string         `json:"updated_at"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateMessageTranslated(ctx context.Context, arg UpdateMessageTranslatedParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageTranslated,
		arg.TranslatedContent,
		arg.Tokens,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
