// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteMessagesByFileID = `-- name: DeleteMessagesByFileID :exec
DELETE FROM messages WHERE file_id = ?
`

func (q *Queries) DeleteMessagesByFileID(ctx context.Context, fileID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteMessagesByFileID, fileID)
	return err
}

const getMaxDisplayOrder = `-- name: GetMaxDisplayOrder :one

SELECT COALESCE(MAX(display_order), 0) AS max_order FROM messages WHERE session_id = ?
`

// NOTE: GetMessagesBySessionCursor uses dynamic cursor logic and is implemented
// as raw SQL in message_repo.go - not generated via SQLC.
func (q *Queries) GetMaxDisplayOrder(ctx context.Context, sessionID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxDisplayOrder, sessionID)
	var max_order interface{}
	err := row.Scan(&max_order)
	return max_order, err
}

const getMessageById = `-- name: GetMessageById :one
SELECT m.id, m.session_id, m.role, m.display_order, m.display_mode, m.original_content, m.translated_content, m.file_id, m.source_lang, m.target_lang, m.style, m.model_used, m.original_message_id, m.tokens, m.created_at, m.updated_at, COALESCE(f.file_size, 0) AS file_size
FROM messages m
LEFT JOIN files f ON f.id = m.file_id
WHERE m.id = ? LIMIT 1
`

type GetMessageByIdRow struct {
	ID                string         `json:"id"`
	SessionID         string         `json:"session_id"`
	Role              string         `json:"role"`
	DisplayOrder      int64          `json:"display_order"`
	DisplayMode       string         `json:"display_mode"`
	OriginalContent   string         `json:"original_content"`
	TranslatedContent sql.NullString `json:"translated_content"`
	FileID            sql.NullString `json:"file_id"`
	SourceLang        sql.NullString `json:"source_lang"`
	TargetLang        sql.NullString `json:"target_lang"`
	Style             sql.NullString `json:"style"`
	ModelUsed         sql.NullString `json:"model_used"`
	OriginalMessageID sql.NullString `json:"original_message_id"`
	Tokens            sql.NullInt64  `json:"tokens"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
	FileSize          int64          `json:"file_size"`
}

func (q *Queries) GetMessageById(ctx context.Context, id string) (GetMessageByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageById, id)
	var i GetMessageByIdRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.DisplayOrder,
		&i.DisplayMode,
		&i.OriginalContent,
		&i.TranslatedContent,
		&i.FileID,
		&i.SourceLang,
		&i.TargetLang,
		&i.Style,
		&i.ModelUsed,
		&i.OriginalMessageID,
		&i.Tokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FileSize,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (
  id, session_id, role, display_order, display_mode,
  original_content, translated_content, file_id, source_lang, target_lang,
  style, model_used, original_message_id, tokens, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	ID                string         `json:"id"`
	SessionID         string         `json:"session_id"`
	Role              string         `json:"role"`
	DisplayOrder      int64          `json:"display_order"`
	DisplayMode       string         `json:"display_mode"`
	OriginalContent   string         `json:"original_content"`
	TranslatedContent sql.NullString `json:"translated_content"`
	FileID            sql.NullString `json:"file_id"`
	SourceLang        sql.NullString `json:"source_lang"`
	TargetLang        sql.NullString `json:"target_lang"`
	Style             sql.NullString `json:"style"`
	ModelUsed         sql.NullString `json:"model_used"`
	OriginalMessageID sql.NullString `json:"original_message_id"`
	Tokens            sql.NullInt64  `json:"tokens"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.DisplayOrder,
		arg.DisplayMode,
		arg.OriginalContent,
		arg.TranslatedContent,
		arg.FileID,
		arg.SourceLang,
		arg.TargetLang,
		arg.Style,
		arg.ModelUsed,
		arg.OriginalMessageID,
		arg.Tokens,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateMessageOriginalContent = `-- name: UpdateMessageOriginalContent :exec
UPDATE messages
SET original_content = ?, updated_at = ?
WHERE id = ?
`

type UpdateMessageOriginalContentParams struct {
	OriginalContent string `json:"original_content"`
	UpdatedAt       string `json:"updated_at"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateMessageOriginalContent(ctx context.Context, arg UpdateMessageOriginalContentParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageOriginalContent, arg.OriginalContent, arg.UpdatedAt, arg.ID)
	return err
}

const updateMessageSourceLang = `-- name: UpdateMessageSourceLang :exec
UPDATE messages SET source_lang = ?, updated_at = ? WHERE id = ?
`

type UpdateMessageSourceLangParams struct {
	SourceLang sql.NullString `json:"source_lang"`
	UpdatedAt  string         `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateMessageSourceLang(ctx context.Context, arg UpdateMessageSourceLangParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageSourceLang, arg.SourceLang, arg.UpdatedAt, arg.ID)
	return err
}

const updateMessageTranslated = `-- name: UpdateMessageTranslated :exec
UPDATE messages
SET translated_content = ?, tokens = ?, updated_at = ?
WHERE id = ?
`

type UpdateMessageTranslatedParams struct {
	TranslatedContent sql.NullString `json:"translated_content"`
	Tokens            sql.NullInt64  `json:"tokens"`
	UpdatedAt         string         `json:"updated_at"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateMessageTranslated(ctx context.Context, arg UpdateMessageTranslatedParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageTranslated,
		arg.TranslatedContent,
		arg.Tokens,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
