// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type File struct {
	ID             string         `json:"id"`
	SessionID      string         `json:"session_id"`
	FileName       string         `json:"file_name"`
	FileType       string         `json:"file_type"`
	FileSize       int64          `json:"file_size"`
	OriginalPath   sql.NullString `json:"original_path"`
	SourcePath     sql.NullString `json:"source_path"`
	TranslatedPath sql.NullString `json:"translated_path"`
	CharCount      sql.NullInt64  `json:"char_count"`
	PageCount      sql.NullInt64  `json:"page_count"`
	Style          sql.NullString `json:"style"`
	ModelUsed      sql.NullString `json:"model_used"`
	Status         string         `json:"status"`
	ErrorMsg       sql.NullString `json:"error_msg"`
	OutputFormat   string         `json:"output_format"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

type Message struct {
	ID                string         `json:"id"`
	SessionID         string         `json:"session_id"`
	Role              string         `json:"role"`
	DisplayOrder      int64          `json:"display_order"`
	DisplayMode       string         `json:"display_mode"`
	OriginalContent   string         `json:"original_content"`
	TranslatedContent sql.NullString `json:"translated_content"`
	FileID            sql.NullString `json:"file_id"`
	SourceLang        sql.NullString `json:"source_lang"`
	TargetLang        sql.NullString `json:"target_lang"`
	Style             sql.NullString `json:"style"`
	ModelUsed         sql.NullString `json:"model_used"`
	OriginalMessageID sql.NullString `json:"original_message_id"`
	Tokens            sql.NullInt64  `json:"tokens"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
	FileSize          int64          `json:"file_size"`
}

type Session struct {
	ID         string         `json:"id"`
	Title      string         `json:"title"`
	Status     string         `json:"status"`
	TargetLang sql.NullString `json:"target_lang"`
	Style      sql.NullString `json:"style"`
	Model      sql.NullString `json:"model"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
}

type Setting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}
