// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
  id, title, status, target_lang, style, model, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID         string         `json:"id"`
	Title      string         `json:"title"`
	Status     string         `json:"status"`
	TargetLang sql.NullString `json:"target_lang"`
	Style      sql.NullString `json:"style"`
	Model      sql.NullString `json:"model"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.TargetLang,
		arg.Style,
		arg.Model,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getSessions = `-- name: GetSessions :many
SELECT id, title, status, target_lang, style, model, created_at, updated_at FROM sessions
WHERE status NOT IN ('deleted', 'archived')
ORDER BY
  CASE WHEN status = 'pinned' THEN 0 ELSE 1 END ASC,
  updated_at DESC
`

func (q *Queries) GetSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.TargetLang,
			&i.Style,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateSessionStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const updateSessionTargetLang = `-- name: UpdateSessionTargetLang :exec
UPDATE sessions SET target_lang = ?, updated_at = ? WHERE id = ?
`

type UpdateSessionTargetLangParams struct {
	TargetLang sql.NullString `json:"target_lang"`
	UpdatedAt  string         `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateSessionTargetLang(ctx context.Context, arg UpdateSessionTargetLangParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionTargetLang, arg.TargetLang, arg.UpdatedAt, arg.ID)
	return err
}

const updateSessionTitle = `-- name: UpdateSessionTitle :exec
UPDATE sessions SET title = ?, updated_at = ? WHERE id = ?
`

type UpdateSessionTitleParams struct {
	Title     string `json:"title"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionTitle, arg.Title, arg.UpdatedAt, arg.ID)
	return err
}
