// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelFileTranslate(arg1) {
  return window['go']['handler']['App']['CancelFileTranslate'](arg1);
}

export function CopyTranslation(arg1) {
  return window['go']['handler']['App']['CopyTranslation'](arg1);
}

export function CreateEmptySession(arg1, arg2, arg3) {
  return window['go']['handler']['App']['CreateEmptySession'](arg1, arg2, arg3);
}

export function CreateSessionAndSend(arg1) {
  return window['go']['handler']['App']['CreateSessionAndSend'](arg1);
}

export function ExportFile(arg1, arg2) {
  return window['go']['handler']['App']['ExportFile'](arg1, arg2);
}

export function ExportMessage(arg1, arg2) {
  return window['go']['handler']['App']['ExportMessage'](arg1, arg2);
}

export function ExportSession(arg1, arg2) {
  return window['go']['handler']['App']['ExportSession'](arg1, arg2);
}

export function GetFileContent(arg1) {
  return window['go']['handler']['App']['GetFileContent'](arg1);
}

export function GetMessages(arg1, arg2, arg3) {
  return window['go']['handler']['App']['GetMessages'](arg1, arg2, arg3);
}

export function GetSessions() {
  return window['go']['handler']['App']['GetSessions']();
}

export function GetSettings() {
  return window['go']['handler']['App']['GetSettings']();
}

export function OpenFileDialog() {
  return window['go']['handler']['App']['OpenFileDialog']();
}

export function ReadFileInfo(arg1) {
  return window['go']['handler']['App']['ReadFileInfo'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['handler']['App']['RenameSession'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['handler']['App']['SaveSettings'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['handler']['App']['SendMessage'](arg1);
}

export function TranslateFile(arg1) {
  return window['go']['handler']['App']['TranslateFile'](arg1);
}

export function UpdateSessionStatus(arg1, arg2) {
  return window['go']['handler']['App']['UpdateSessionStatus'](arg1, arg2);
}
