// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {model} from '../models';

export function CancelFileTranslate(arg1:string):Promise<void>;

export function CopyTranslation(arg1:string):Promise<string>;

export function CreateEmptySession(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateSessionAndSend(arg1:bridge.CreateSessionAndSendRequest):Promise<bridge.CreateSessionAndSendResult>;

export function ExportFile(arg1:string,arg2:string):Promise<string>;

export function GetFileContent(arg1:string):Promise<bridge.FileContent>;

export function GetMessages(arg1:string,arg2:number,arg3:number):Promise<bridge.MessagesPage>;

export function GetSessions():Promise<Array<model.Session>>;

export function GetSettings():Promise<model.Settings>;

export function OpenFileDialog():Promise<string>;

export function ReadFileInfo(arg1:string):Promise<bridge.FileInfo>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:model.Settings):Promise<void>;

export function SendMessage(arg1:bridge.SendRequest):Promise<string>;

export function TranslateFile(arg1:bridge.FileRequest):Promise<void>;

export function UpdateSessionStatus(arg1:string,arg2:string):Promise<void>;
